### ISSUE TITLE
Could not find @ReactModule annotation in org.mauritsd.reactnativedynamicbundle.RNDynamicBundleModule

### ISSUE THREAD

**Issue by jdnichollsc** [mauritsd/react-native-dynamic-bundle#4]
Hello mate, I can see the following issue from Android:
```

02-19 16:38:54.943 19411-19411/com.modularapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.modularapp, PID: 19411
    java.lang.IllegalArgumentException: Could not find @ReactModule annotation in org.mauritsd.reactnativedynamicbundle.RNDynamicBundleModule
        at com.facebook.react.bridge.CatalystInstanceImpl.getNameFromAnnotation(CatalystInstanceImpl.java:444)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:433)
        at com.facebook.react.bridge.ReactContext.getNativeModule(ReactContext.java:119)
        at com.modularapp.MainActivity$1.onReactContextInitialized(MainActivity.java:39)
        at com.facebook.react.ReactInstanceManager$6.run(ReactInstanceManager.java:1018)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by jdnichollsc** [comment]
@mauritsd works perfect from iOS device: https://github.com/proyecto26/react-native-modular

I owe you one! 👍
