### ISSUE TITLE
Error activating a bundle from Android (release)

### ISSUE THREAD

**Issue by jdnichollsc** [mauritsd/react-native-dynamic-bundle#8]
Hi @mauritsd 
I'm reviewing from Android (release mode) but there's an issue after active a bundle:
- react-native run-android --variant=release
```
02-28 23:47:21.404 6141-6192/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
```
- From the signed apk
```
03-01 00:33:05.726 25275-25294/? D/ReactNative: Initializing React Xplat Bridge.
03-01 00:33:05.729 25275-25294/? D/ReactNative: Initializing React Xplat Bridge before initializeBridge
03-01 00:33:05.734 25275-25294/? D/ReactNative: Initializing React Xplat Bridge after initializeBridge
    CatalystInstanceImpl.runJSBundle()
03-01 00:33:05.735 25275-25311/? D/ReactNative: ReactInstanceManager.setupReactContext()
    CatalystInstanceImpl.initialize()
03-01 00:33:05.735 25275-25311/? D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
03-01 00:33:06.001 25275-25310/? E/ReactNativeJS: undefined is not a function (evaluating 'this._nativeModule.addListener(eventType)')
03-01 00:33:06.176 25275-25310/? E/ReactNativeJS: undefined is not an object (evaluating 'viewConfig.Manager')
03-01 00:33:06.185 25275-25310/? W/ReactNativeJS: Unable to symbolicate stack trace: Bundle was not loaded from the packager
    Unable to symbolicate stack trace: Bundle was not loaded from the packager
03-01 00:33:06.186 25275-25310/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
03-01 00:33:06.188 25275-25310/? W/ReactNativeJS: Unable to symbolicate stack trace: Bundle was not loaded from the packager
03-01 00:33:06.265 25275-25275/? D/ReactNative: ReactInstanceManager.detachViewFromInstance()
03-01 00:33:06.267 25275-25310/? E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling unmountApplicationComponentAtRootTag)
03-01 00:33:06.274 25275-25310/? W/ReactNativeJS: Unable to symbolicate stack trace: Bundle was not loaded from the packager
```
After that, the app is crashing all the time when I try to open it again

What do you think? This is the repo: https://github.com/proyecto26/react-native-modular/tree/dynamic-bundle

**Comment by jdnichollsc** [comment]
More details about this issue:
```
03-04 10:21:31.663 4974-5011/? I/libprocessgroup: Successfully killed process cgroup uid 5018 pid 3577 in 52ms
03-04 10:21:31.704 5237-5290/? E/ReactNativeJS: undefined is not a function (evaluating 'this._nativeModule.addListener(eventType)')
03-04 10:21:31.717 4974-10871/? D/MdnieScenarioControlService:  packageName : com.modularapp    className : com.modularapp.MainActivity
03-04 10:21:31.717 4974-10871/? V/MdnieScenarioControlService: setUIMode from UI function(3)

    --------- beginning of crash
03-04 10:21:31.726 5237-5291/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.modularapp, PID: 5237
    com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'this._nativeModule.addListener(eventType)'), stack:
    addListener@27674:41
    AppState@30233:24
    <unknown>@30311:28
    loadModuleImplementation@265:14
    guardedLoadModule@161:38
    metroRequire@88:92
    <unknown>@30162:31
    loadModuleImplementation@265:14
    guardedLoadModule@161:38
    metroRequire@88:92
    <unknown>@30147:20
    loadModuleImplementation@265:14
    guardedLoadModule@161:38
    metroRequire@88:92
    <unknown>@23206:16
    loadModuleImplementation@265:14
    guardedLoadModule@153:47
    metroRequire@88:92
    global code@161022:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by amirasaran** [comment]
Are you fix this issue?

**Comment by hasgardee** [comment]
any fix ?
